In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn import linear_model

In [2]:
bbdata = pd.read_csv("D:\Datasets For ML & DS Practice\Baseball_League_Data.csv")

In [3]:
bbdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 353 entries, 0 to 352
Data columns (total 47 columns):
salary      353 non-null int64
teamsal     353 non-null int64
nl          353 non-null int64
years       353 non-null int64
games       353 non-null int64
atbats      353 non-null int64
runs        353 non-null int64
hits        353 non-null int64
doubles     353 non-null int64
triples     353 non-null int64
hruns       353 non-null int64
rbis        353 non-null int64
bavg        353 non-null float64
bb          353 non-null int64
so          353 non-null int64
sbases      353 non-null int64
fldperc     353 non-null int64
frstbase    353 non-null int64
scndbase    353 non-null int64
shrtstop    353 non-null int64
thrdbase    353 non-null int64
outfield    353 non-null int64
catcher     353 non-null int64
yrsallst    353 non-null int64
hispan      353 non-null int64
black       353 non-null int64
whitepop    330 non-null float64
blackpop    339 non-null float64
hisppop     330 non-null float64
pcinc       353 non-null int64
gamesyr     353 non-null float64
hrunsyr     353 non-null float64
atbatsyr    353 non-null float64
allstar     353 non-null float64
slugavg     353 non-null float64
rbisyr      353 non-null float64
sbasesyr    353 non-null float64
runsyr      353 non-null float64
percwhte    330 non-null float64
percblck    330 non-null float64
perchisp    330 non-null float64
blckpb      330 non-null float64
hispph      330 non-null float64
whtepw      330 non-null float64
blckph      330 non-null float64
hisppb      330 non-null float64
lsalary     353 non-null float64
dtypes: float64(21), int64(26)
memory usage: 129.7 KB

In [4]:
bbdata.describe()

,salary,teamsal,nl,years,games,atbats,runs,hits,doubles,triples,...,runsyr,percwhte,percblck,perchisp,blckpb,hispph,whtepw,blckph,hisppb,lsalary
count,3.530000e+02,3.530000e+02,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000,...,353.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,353.000000
mean,1.345672e+06,3.079483e+07,0.475921,6.325779,648.424929,2168.592068,290.402266,584.736544,103.881020,16.733711,...,38.582988,72.631088,16.548926,10.819986,5.144886,2.004179,36.667635,2.931898,3.046493,13.492183
std,1.407352e+06,8.722411e+06,0.500129,3.880142,538.697499,2025.059766,301.010915,575.378562,104.323511,21.533336,...,23.862686,15.227258,13.668326,9.387961,11.109446,5.858419,37.637047,6.667690,8.415198,1.182466
min,1.090000e+05,8.854000e+06,0.000000,1.000000,7.000000,7.000000,1.000000,1.000000,0.000000,0.000000,...,0.500000,20.296301,3.741786,0.540870,0.000000,0.000000,0.000000,0.000000,0.000000,11.599103
25%,2.536000e+05,2.455733e+07,0.000000,3.000000,230.000000,632.000000,73.000000,164.000000,26.000000,3.000000,...,18.600000,67.668961,8.007545,1.962080,0.000000,0.000000,0.000000,0.000000,0.000000,12.443514
50%,6.750000e+05,3.413650e+07,0.000000,6.000000,520.000000,1585.000000,191.000000,419.000000,70.000000,9.000000,...,35.333332,74.131294,14.453978,10.877804,0.000000,0.000000,20.296301,0.000000,0.000000,13.422468
75%,2.250000e+06,3.779200e+07,1.000000,9.000000,930.000000,3071.000000,407.000000,818.000000,147.000000,23.000000,...,55.888889,82.948860,18.755629,16.330647,7.986870,0.000000,73.642937,1.561949,0.000000,14.626441
max,6.329213e+06,4.286600e+07,1.000000,20.000000,2729.000000,10554.000000,1570.000000,3025.000000,634.000000,142.000000,...,105.142860,94.696266,73.960030,31.037498,73.960030,31.037498,94.696266,31.037498,73.960030,15.660686

In [5]:
bbdata = bbdata.dropna()

In [6]:
bbdata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 330 entries, 0 to 352
Data columns (total 47 columns):
salary      330 non-null int64
teamsal     330 non-null int64
nl          330 non-null int64
years       330 non-null int64
games       330 non-null int64
atbats      330 non-null int64
runs        330 non-null int64
hits        330 non-null int64
doubles     330 non-null int64
triples     330 non-null int64
hruns       330 non-null int64
rbis        330 non-null int64
bavg        330 non-null float64
bb          330 non-null int64
so          330 non-null int64
sbases      330 non-null int64
fldperc     330 non-null int64
frstbase    330 non-null int64
scndbase    330 non-null int64
shrtstop    330 non-null int64
thrdbase    330 non-null int64
outfield    330 non-null int64
catcher     330 non-null int64
yrsallst    330 non-null int64
hispan      330 non-null int64
black       330 non-null int64
whitepop    330 non-null float64
blackpop    330 non-null float64
hisppop     330 non-null float64
pcinc       330 non-null int64
gamesyr     330 non-null float64
hrunsyr     330 non-null float64
atbatsyr    330 non-null float64
allstar     330 non-null float64
slugavg     330 non-null float64
rbisyr      330 non-null float64
sbasesyr    330 non-null float64
runsyr      330 non-null float64
percwhte    330 non-null float64
percblck    330 non-null float64
perchisp    330 non-null float64
blckpb      330 non-null float64
hispph      330 non-null float64
whtepw      330 non-null float64
blckph      330 non-null float64
hisppb      330 non-null float64
lsalary     330 non-null float64
dtypes: float64(21), int64(26)
memory usage: 123.8 KB

In [7]:
#3 Independent Variables

In [8]:
X = bbdata[['years','games','atbats']]
Y = bbdata['salary']
  
# with sklearn
regr = linear_model.LinearRegression()
regr.fit(X, Y)
 
print('Intercept: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)

Intercept:
 767559.6442907361
Coefficients:
 [-141960.3950284      233.13940275     608.97308568]

In [9]:
# with statsmodels
X = sm.add_constant(X) # adding a constant
  
model = sm.OLS(Y, X).fit()
predictions = model.predict(X) 
  
print_model = model.summary()
print(print_model)

                            OLS Regression Results
==============================================================================
Dep. Variable:                 salary   R-squared:                       0.411
Model:                            OLS   Adj. R-squared:                  0.406
Method:                 Least Squares   F-statistic:                     75.80
Date:                Mon, 20 Aug 2018   Prob (F-statistic):           3.20e-37
Time:                        18:48:19   Log-Likelihood:                -5048.7
No. Observations:                 330   AIC:                         1.011e+04
Df Residuals:                     326   BIC:                         1.012e+04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       7.676e+05    1.3e+05      5.918      0.000    5.12e+05    1.02e+06
years       -1.42e+05   5.66e+04     -2.507      0.013   -2.53e+05   -3.06e+04
games        233.1394   1181.155      0.197      0.844   -2090.508    2556.787
atbats       608.9731    243.479      2.501      0.013     129.985    1087.961
==============================================================================
Omnibus:                       43.482   Durbin-Watson:                   1.344
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               64.805
Skew:                           0.835   Prob(JB):                     8.47e-15
Kurtosis:                       4.387   Cond. No.                     7.03e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.03e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [10]:
#7 Independent Variables

In [11]:
X = bbdata[['years','games','atbats','hits','bavg','outfield','catcher']]
Y = bbdata['salary']
  
# with sklearn
regr = linear_model.LinearRegression()
regr.fit(X, Y)
 
print('Intercept: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)

Intercept:
 -426489.34491544706
Coefficients:
 [-156054.56400431     744.35061605     266.30916779     741.81699405
    4605.13497506   86855.33030714  255661.58294836]

In [12]:
# with statsmodels
X = sm.add_constant(X) # adding a constant
  
model = sm.OLS(Y, X).fit()
predictions = model.predict(X) 
  
print_model = model.summary()
print(print_model)

                            OLS Regression Results
==============================================================================
Dep. Variable:                 salary   R-squared:                       0.427
Model:                            OLS   Adj. R-squared:                  0.414
Method:                 Least Squares   F-statistic:                     34.25
Date:                Mon, 20 Aug 2018   Prob (F-statistic):           1.51e-35
Time:                        18:48:19   Log-Likelihood:                -5044.1
No. Observations:                 330   AIC:                         1.010e+04
Df Residuals:                     322   BIC:                         1.013e+04
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -4.265e+05   5.55e+05     -0.768      0.443   -1.52e+06    6.66e+05
years      -1.561e+05   5.97e+04     -2.614      0.009   -2.74e+05   -3.86e+04
games        744.3506   1237.029      0.602      0.548   -1689.329    3178.030
atbats       266.3092    466.236      0.571      0.568    -650.945    1183.563
hits         741.8170   1152.924      0.643      0.520   -1526.397    3010.031
bavg        4605.1350   2107.159      2.185      0.030     459.598    8750.672
outfield    8.686e+04   1.28e+05      0.679      0.498   -1.65e+05    3.38e+05
catcher     2.557e+05   1.89e+05      1.350      0.178   -1.17e+05    6.28e+05
==============================================================================
Omnibus:                       39.976   Durbin-Watson:                   1.350
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               57.639
Skew:                           0.793   Prob(JB):                     3.05e-13
Kurtosis:                       4.295   Cond. No.                     3.04e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.04e+04. This might indicate that there are
strong multicollinearity or other numerical problems.